flowchart LR
    管理者((管理者))
    家長教師(("家長／教師"))

    subgraph 成績管理子系統
        direction TB
        UC04a([查詢兒童歷史成績])
        UC04b([新增或修改成績])
        UC04c([刪除成績記錄])
    end

    管理者  --> UC04a
    管理者  --> UC04b
    管理者  --> UC04c
    家長教師 --> UC04a