flowchart LR
    施測者((施測者))
    兒童((兒童))

    subgraph 施測流程子系統
        direction TB
        UC02a([輸入兒童 UID])
        UC02b([選擇測驗關卡])
        UC02c([啟動攝影機])
        UC02d([執行任務與拍照])
        UC02e([提交影像分析])
    end

    施測者 --> UC02a
    施測者 --> UC02b
    施測者 --> UC02c
    施測者 --> UC02d
    施測者 --> UC02e
    兒童  --> UC02d