flowchart LR
    管理者((管理者))

    subgraph 兒童帳號管理子系統
        direction TB
        UC01a([新增兒童帳號])
        UC01b([查詢兒童資料])
        UC01c([刪除兒童帳號])
    end

    管理者 --> UC01a
    管理者 --> UC01b
    管理者 --> UC01c